{% set name = "flake8-no-pep420" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flake8_no_pep420-{{ version }}.tar.gz
  sha256: 37e2cc47400033de66aa826bd08994aa6f9a2fdf9dfb9705723ff7946812019e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - flake8 !=3.2.0,>=3.0

test:
  imports:
    - flake8_no_pep420
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/adamchainz/flake8-no-pep420
  summary: A flake8 plugin to ban PEP-420 implicit namespace packages.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
